project:
  type: website
  render: 
    - "*.qmd"
    - "!assignments/"

website:
  title: "GEOG 4022: Geomorphology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - class-notes.qmd
      - lab.qmd

number-sections: true
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

