---
title: "Class notes"
---

# What is geomorphology?

**2026-08-26**

- The study of landforms and the processes that create them
- Study of Earth's dynamic surface, its history, and its active processes
- Around since Ancient Greece, but term coined in late 1800s

> “Geomorphologists learn to observe and interpret landscapes systematically in order to understand how processes shape Earth’s surface, decipher the history of a place, and recognize (and potentially mitigate or manage) the impacts of environmental hazards on societies”
> 
> --- Bierman and Montgomery, 2014

**Interdisciplinary science**

- Synthetic science: geography, geology, physics, chemistry, biology, etc.
- Qualitative & quantitative
- Nexus of lithosphere (geosphere), hydrosphere, biosphere, atmosphere

## Facets of geomorphology

- Morphology (static)
    - Constitution
    - Configuration
    - Mass flow (discharge, precipitation rate, sediment flux---still static rates of flow)
- Dynamic variables
    - Chemical & mechanical properties representing energy expenditure & doing of work (power, force, stress, momentum, etc.)
    
Beach example (in PPT)

## Approaches

- In US, geomorphology courses taught in both physical geography & geology departments
- In the past, focus on description and classification of landforms to inform landscape history
- Since 1950s (or a bit earlier in the century), push toward quantitative characterisation and understanding of *process* (especially physical and chemical processes)

## Themes

Lots of themes, lots of valid dichotomies

- Reductionism vs synthesis
- Quantitative vs qualitative
- Complexity vs similarity
- Mechanistic (process) vs event/extremal hypotheses
- High-tech vs low-tech
- Large vs small scales
- Field vs lab/numerical modelling studies
- REMOTE SENSING

## Historical geomorphology

- Study of landform genesis & evolution over medium to long time scales
- WM Davis (geographer, one of founders of AAG) introduced concept of The Geographical Cycle: landscapes undergo initial and sudden uplift, then geomorphic processes continue gradually wearing down topography (increase in relief). Stages are youthful, mature, old age.
- Especially these terminologies were very simplistic, and not very popular now.
- Currently, relies on advanced dating techniques to reconstruct Quaternary history of a region (now--2.5mya)

## Process geomorphology

- Study of processes responsible for landform development & geomorphic change
- GK Gilbert defined (1877, *Geology of Henry Mountains*) concept of **dynamic equilibrium** between driving forces and resistance of geologic structure
    - Father of modern geomorphology: first to associate mechanical principles with geomorphic action
    - USGS, background in physics and geology
    - President of GSA & AAG
- Post-Gilbert:
    - Robert Horton: hydrophysical approaches to study fluvial systems
    - Arthur Strahler: advocated for dynamic geomorphology
    - 1950s--60s: explosion of quantitative process-based studies, emphasis on equilibrium (self-regulation) in fluvial systems (systems concepts)
    - 1970s: slow shift to disequilibrium
    - 1980s: renewed interest in systems approaches
    - 1990s--recent: non-linear dynamics, numerical & physical modelling, sophistication of field techniques & tech
    - Morphodynamics: study of landscape evolution as it relates to deposition and erosion of sediment (Gary Parker)
    
**Arguments against (1980s)**

- Small scale processes, reductionism
- Emphasis on applied (becoming nothing more than engineering)
- "The re-enchantment of geomorphology", Vic Baker and Rollie Twidale (1991)

## Reenchanctment of geomorphology

- Critical of Process Geomorphology (4 main concerns)
    - Anti-historicism (ignoring rare/extreme events)
    - Over-reliance on physical theory (theoreticism diverts attention from observation, first step of scientific method)
    - Increasing emphasis on applied studies: becoming engineering, application should not drive science
    - Over-emphasis on modelling: sophistication replacing accuracy
- Solution: **maverick geomorphology** (anomalies, creativity & discovery, non-theoretical historical studies)

## Subgroups of geomorphology

- Tectonic: interaction between tectonic & geomorphic processes where crust actively deforms; interest in orogenies (mountain building)
- Climatic: some proponents suggest climatic zones (tropics, arid, etc.) engenders a distinctive suite of landforms, but highly contested, more to it (though climate does have strong influence)
    - Physiographic provinces: at regional scales, tectonic forces and climatic conditions create distinct provinces, producing similar landforms
- Hydro-: hydrology + geomorphology
- Bio-/eco- (plants or animals)
- Biomorphodynamics: biological-physical feedbacks between animals and plants and physical geomorphic processes
- Anthropo-, submarine, planetary (lots more)
- Exact terms don't matter, conceptual syntheses

Fig 1. from Steiger & Corenblit 2012 is nice for my perspective. But Kory disagrees with bio- being only passive manipulators of Earth surface processes (also active).

# Methods for Geomorphic Science

**2026-08-28**

## Common variables of interest

- Water velocity and discharge (volumetric flow rate)
    - Classic propeller-meters for 1d measurement
    - Acoustic Doppler Velocimeter for 3d velocity components (at-a-point, time-series)
    - Acoustic Doppler Current Profiler (ADCP): newer, good for larger faster sampling
    - Large-scale particle image velocimetry (LS-PIV): originated as lab method; add some particle and measure its flow
- Channel morphology
    - Width, depth
    - Bed, bedform
    - Bankline delineation, bank roughness
    - Direct field surveying (total station, GPS)
    - Remote sensed: 
    - LiDAR great for "subtracting" vegetation (aerial), also high-res imaging especially vertical (terrestrial, TLS)
    - Drones: morphologic and sedimentological mapping
    - Structure from mapping
    - River bathymetry mapping: LiDAR doesn't work well with water (mostly due to sediment), but Multibeam Echo Sounding (MBES) is high-res, mount on boat and go across river; hydroacoustics, get multiple streams of info about elevation (1000 pings per swath, ADCP only 4); ADCP maps velocities, MBES maps river and coastal beds
- Mapping subsurface
    - Ground Penetrating Radar (GPR): cart pulled across ground
    - Sediment and soil coring: manual hammering or vibracore (vibrating weight on top)
        - Sizing: Dry sieving (Roto-tap) with multiple sieves, gives grain size distribution (proportional masses)
- Numerical Morphodynamic Modelling
- Satellite remote sensing, automated river migration methods

## Basic principles of Geomorphology

**2026-08-31**

- Systems science
    - System: set of interrelated things linked by flows (input-output) and distinct from surrounding environment (input-output cross some boundary)
    - Each geomorphic system (e.g., rivers) is its own system
    - Input minus output = storage change ($I - O = \Delta ST$; Conservation Laws of Mass and Energy)
    - Types of systems:
        - Open: exchange both energy and matter with surrounding environment (most geomorphic systems)
        - Closed: exchange only energy with surrounding environment (global concepts, e.g., hydrological system)
        - Isolated: cannot exchange energy or matter with surrounding environment (theoretical concept)
    - Feedbacks
        - As systems operate, generate outputs that influence aspects of the system---**feedbacks**
        - **Feedback loop**: pathway that information about system travels between various points of system (snowball vs self-regulation)
- Uniformitarianism
    - In late 19th century, shift from catastrophism to uniformitarianism
    - **Catastrophism:** change by sudden, rapid, violent events (doesn't require long periods of time)
    - **Gradualism:** slow, gradual change (long periods of time); introduced by James Hutton in *Theory of the Earth* (1795)
    - **Uniformitarianism:** 
        - laws of physics and natural processes operating today are same as those in past (vast, long geologic history)
        - Charles Lyell in *Principles of Geology* (1830)
        - includes both slow changes and major events (floods, earthquakes)
- Principles of Equilibrium, Thresholds & Complex Response 
    - Delicate balance between landforms and processes
    - Always consider driving forces vs resisting forces
    - **Steady-state:** rates of input and output are equal; system maintains time-averaged level
    - **Metastable/Complex Response:** when system reaches some **threshold** (tipping point), it abruptly shifts to a different state which may later reach steady-state equilibrium
    - **Dynamic:** (depends on time scale of interest) appears in steady-state over short term, but there is some trend over long term
    - Evaluating a system's equilibrium condition requires consideration of temporal scale & capabilities to assess change over that time period
- Process-form relationship
    - Mediated by energy, force and resistance (driving vs resisting force)
    - We can view a lot of our systems through the framework of what's trying to do the work and what's trying to hold it in place
- Recurrence Intervals & Magnitude-Frequency relationships
    - Most geomorphic change comes from discrete events of varying size and scale (therefore, magnitude)
    - RI: average time between events of a given magnitude
    - Aug 2016 in Baton Rouge (Lafayette to Slidell): huge flood, magnitude super high (500-1000 year event), but doesn't mean we cannot have similar in the near future
    - Using all these in analyses (especially predicting large events) requires that the system we're modelling doesn't change in properties, but this is generally not the case
- Landscapes based on sensitivity
    - **Insensitive/robust:** steady-state, "buffering", system responds fast to external forces
    - **Sensitive:** slow to response to external forces, or timing of forces faster than response; complex response
    - Landscape Sensitivity based on transient-form ratio (mean recovery time/mean recurrence interval): larger $TF_r$ means more sensitive landscape
    
$$
TF_r = \frac{t_r}{t_d}
$$

# Endogenic Processes & Earth Basics

- **Endogenic:** internal processes related to movement of lithosphere (tectnoics) and/or eruption of molten rock (volcanism)
    - Responsible generally for increasing elevation of landscapes
    - Generally build up (driving force)
    - Larger time scales
- **Exogenic:** external processes related to overall wearing down of landscapes (weather, water, wind, ice)
    - Generally wearing down (resisting force)

## Geologic Time Scale

**2026-09-02**

- Eons --> Eras --> Periods --> Epochs
- Precambrian eon actually has 3 eons, but largely grouped together
- Boundaries based on key events in Earth's history (Earth's physical form, atmospheric composition, evolution/dominance of various forms of life)
    - Precambrian-Phanerozoic boundary represents **Cambrian Explosion**: modern atmospheric composition & variety and complexity of life increased rapidly and enormously (suddenly lots of fossils)
    - Within Phanerozoic, based on extinctions and evolution
    - PT extinction (largest) was due to volcanic activity, not asteroid
- Cenozoic: modern is Palaeogene, Neogene, Quaternary
    - Pleistocene = last glaciation (2.6mya--10kya)
    - Strong push to add Anthropocene Epoch to GTS: when? Weapons of mass destruction (mid-1900s), or *industrialisation*?
        - Only scientific argument against: we don't know what the *lasting evidence* will be, cos no historical record as such to track

## Earth's interior

- Internal heat drives endogenic processes
- Core (50%): inner is solid iron, outer is molten iron
    - Heat from compaction during formation, and from radioactive decay
    - Heat allows mantle elements to move (mantle convection)
- Uppermost mantle is rigid but much denser than crust above
- Crust vs mantle (density); lithosphere vs asthenosphere (rigidity)
- Top 1% is crust: continental (granite; thicker; slightly less dense) & oceanic (basalt; thinner; slightly denser)
    - **Isostasy:** adjustment of asthenosphere to lithosphere based on density-thickness differences; keeps gravity and buoyancy in equilibrium; erosion of crust might result in uplift of plate
    - Spatial distribution of both crust types across globe different

## Plate tectonics

- Seven major tectonic plates
- Only around 1960s correlational evidence among plate shapes, earthquake hotspots, and volcanic activity came together to conceptualise plate tectonics
    - Only after WWII! With more geophysical evidence, pinpoint *how* these movements happen
    - **How:** mantle convection + gravity
    - Earlier concepts thought of continents as icebergs in the oceanic sea
    - But now we know the whole lithospheric crust moves
    - Zero sum game: volcanic activity builds material, on the other end **subduction**
        - Gravity pulls one plate below another through subduction (usually in basaltic ocean crust); mantle convection adds new material atop the crust
- **Tectonic boundaries:** divergent, transform, convergent
- Continent-continent convergent boundaries: **suture zones** (no scope for subduction due to thickness, equal density) resulting in orogeny
- Ocean-continent convergence: subduction due to oceanic being denser and thinner
- Ocean-ocean: older colder (denser) oceanic subducts under younger 
- When plate gets subducted: 
    - Part of it starts melting, becomes less dense, and results in more volcanic activity
    - The higher plate also "scrapes" off subducted plate, either forming some wedge or collecting smaller islands 
- **Bowen's reaction series:** sequence in which minerals crystallise/melt from magma/rock
    - High to low temperature increases silica content (earliest rocks formed have lower, latest/youngest have more silica)
    - Silica content determines resistance to breaking down at Earth's surface (more silica, more resistant; e.g., sand on beaches)