---
title: "Review of Phillips (2016)"
bibliography: ../references.bib
csl: "../geomorphology.csl"
format: 
  docx:
    reference-doc: "../word_template.docx"
    number-sections: false
---

# Summary

In this paper, the author describes a framework that can be useful when thinking about Earth surface systems (ESS). In this framework, all possible factors responsible for the state of a system at any point can be distilled into three axes: law, place, and history (LPH). Law here refers to *general* principles, ranging from fundamental laws in physics and chemistry to broad relationships in geology, geography, biology, hydrology, etc. These laws are applicable multiple systems, independent of context, and can therefore be thought of as non-contingent factors. On the other hand, the state of a system is also affected by several unique, contingent factors. Place factors attribute certain general or specific properties to the system through spatial or geographical context. History factors effect contingency through path-dependence, ranging from sensitivity to the initial state, to evolutionary pathways and stages, and even available time. 

The author presents this triadic framework as a useful pedagogical and analytic tool. The ideas on which the framework is built are not novel or revolutionary; the fundamental dichotomy of global and local controls has been conceptualised in various ways over the course of development of the field. For instance, @simpson1963 described immanent and configurational factors, while @schumm1991 referred to the local contingent factors as singularities, which have even been linked to non-linear complexity and historical contingency. In philosophy, this is conceptualised as necessary versus contingent factors. The triadic LPH frameworkm, however, argues for explicitly and separately considering both geographical and historical contingency. Even this has antecedents, such as WM Davis's strictly geologic process-structure-time model [@davis1902], and the much younger epidemiological triangle [@gatrell2014] follows a similar logic. Although the LPH framework demands that all three categories of factors be considered, it does not necessarily define them as mutually exclusive. 

The author uses three case studies to demonstrate the utility of this framework. First, he shows that LPH can serve as a useful explanatory checklist in pedagogy, using the example of Mammoth Cave, USA. While this is a strikingly unique system, it is helpful to start with the laws or principles that apply to any cave, which also comprise the foundation of this system. This then makes it easier to focus on what makes Mammoth Cave unique: place factors such as presence of thick limestone and insoluble sandstone caprock, and historical factors such as age and incision history of the Green River. 

Then, the utility of the LPH framework as an analytical tool is demonstrated in two ways. Accounting for differences in place and history factors can help get to the shared general laws governing a system; this is shown using the example of the Ouachita Mountains in Arkansas, USA, where predominantly taproot tree roots accelerate rock weathering and result in greater regolith formation. On the other hand, differences among case studies can be reconciled and narrowed down by first accounting for the factors that are shared, then isolating potentially contingent place and history factors. This is demonstrated with the example of three rivers in southeast Texas, which are all governed by the same laws relating to alluvial rivers and broad-scale place and history factors. Here, the differences instead largely relate to local-scale place factors determining avulsion regimes.

# Critique

My first reaction reading through the author's argument was confusion regarding the particular novelty of this framework. In studies of many ESS, including biological systems, it is common practice to disentangle global forces from local ones, and spatial factors from temporal ones. Moreover, in many of these disciplines dealing with systems of greater complexity (relative to those in the "harder" sciences of physics and chemistry), the dichotomy of contingent and non-contingent factors is also very familiar. In fact, contingency is so prevalent and striking in ecological systems that it is very difficult to find general laws that are truly independent of context [@lawton1999].

However, as I got closer to the end of his argument, it became clearer to me that the author simply intends for this framework to connect several different ideas that are often disconnected and treated in isolation. The point is to explicitly consider differences between local and global factors, and spatial and temporal factors, and finally both contingent and non-contingent factors. The LPH framework places contingent and non-contingent factors on equal footing, and this to me is critical: very often, even in disciplines like ecology, attention is often drawn exclusively to one over the other, and this can be detrimental. 

While the framework itself was explained well in clear language, the case studies used to demonstrate its utilities were rather difficult to follow, especially for someone not well versed in the field. The text became jargon-heavy, and the explanations could have done with more and better-visualised diagrams. The three axes in the LPH framework not being mutually exclusive is good in many ways, but can also diminish the analytical clarity that the framework is supposed to provide. Overall, I also do wonder how its utility may reduce in cases where there are fewer and fewer general laws applicable independent of context, as in many ecological systems. Axiomatically searching for these laws can end up being a futile exercise if they are so basic and general as to not hold much explanatory power for the system of interest, whereas isolating place and history factors would simultaneously become a more vague and challenging exercise.

# References